<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Depository.Extensions.DependencyInjection\Depository.Extensions.DependencyInjection.csproj" />
      <ProjectReference Include="..\Depository\Depository.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="6.12.1" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
      <PackageReference Include="TUnit" Version="1.17.25" />
    </ItemGroup>

</Project>
