name: Benchmark For Depository
on:
  push:
    branches:
      - benchmark/*
  pull_request:
    branches:
      - benchmark/*
        
permissions:
  contents: write
  deployments: write      
  
jobs:
  benchmark:
    name: Run Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Run benchmark
        run: cd Depository.Benchmarks && dotnet run -c Release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: benchmark-result
          path: Depository.Benchmarks/BenchmarkDotNet.Artifacts
          
          
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark.Net Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: Depository.Benchmarks/BenchmarkDotNet.Artifacts/results/Depository.Benchmarks.Benchmarks-report-full-compressed.json
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          auto-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
          alert-comment-cc-users: '@kengwang'
      
      - name: Store Result in Another Place
        run: |
          mkdir -p ${{ runner.temp }}/benchmark-result
          cp -r Depository.Benchmarks/BenchmarkDotNet.Artifacts/ ${{ runner.temp }}/benchmark-result
          
      - name: Checkout Github Page
        uses: actions/checkout@v2.6.0
        with:
          ref: gh-pages
            
      - name: Restore Result
        run: |
          mkdir -p bench/${{ github.sha }}
          cp -r ${{ runner.temp }}/benchmark-result bench/${{ github.sha }}
          
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Benchmark on ${{ github.sha }}