name: Depository.Core Unit Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        mode: [jit]
        include:
          - os: windows-latest
            mode: aot
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test (JIT)
      if: matrix.mode == 'jit'
      run: dotnet test Depository.Tests/Depository.Tests.csproj -c Release --verbosity normal
    - name: Publish (AOT)
      if: matrix.mode == 'aot'
      run: dotnet publish Depository.Tests/Depository.Tests.csproj -c Release -r ${{ matrix.rid }} -o ${{ github.workspace }}/out/aot
    - name: Run (AOT)
      if: matrix.mode == 'aot'
      run: ${{ github.workspace }}/out/aot/Depository.Tests.exe
